### ISSUE TITLE
Dependency tree error when installing on react-native 0.73.6

### ISSUE THREAD

**Issue by mbaviera** [DevChanQ/react-native-svg-editor#1]
Hello, the following error is occurring when running npm i react-native-svg-editor --save on react-native 0.73.6. Could this be related to library dependencies?

![Captura de Tela 2024-03-21 às 10 01 50](https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/28e91681-04f3-41c9-bfe3-e54b9c89588d)

![Captura de Tela 2024-03-21 às 17 07 18](https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/89242329-f31b-4a58-b824-93e1828856b2)

**Comment by DevChanQ** [comment]
Hey thanks for letting me know!

The library was originally built for react native 0.69 so there maybe some problem with dependencies. I am in the process of making the library compatible with the latest version of react native but feel free to mess around with it as well :)

**Comment by DevChanQ** [comment]
@mbaviera I just pushed new commits to the package, as well as instructions about installing peer dependencies in the README. Try it out & it should be working correctly :)

**Comment by mbaviera** [comment]
Hi @DevChanQ thanks for the work! I'm trying to run it and I think I found some other problems.

1 -

<img width="955" alt="Captura de Tela 2024-03-24 às 09 41 42" src="https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/82d14487-b877-4b5d-8a71-deb3dce2ca4c">

and the solution I found was to change the name to .js

![Captura de Tela 2024-03-24 às 09 43 58](https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/13cd4927-94ab-4fa5-98e9-70093e4dc786)

2 - 

fix getBBox import

![Captura de Tela 2024-03-24 às 09 49 54](https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/5ff27074-b7dd-4a61-8e29-305fc3408d91)


3 - 
<img width="844" alt="Captura de Tela 2024-03-24 às 09 47 07" src="https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/80f0ccf7-d51c-4821-9050-36ea89f22312">

and the resolution I believe is something like:

![Captura de Tela 2024-03-24 às 09 48 03](https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/ceed44eb-7972-49f6-adae-2c4f22582523)


After doing this I managed to make it run, but I believe there is still a problem, this is the result I found:

<img width="445" alt="Captura de Tela 2024-03-24 às 09 52 53" src="https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/7042a61d-bd86-43a2-88e9-cadb43a24c0e">

**Comment by DevChanQ** [comment]
Nice work! I have updated the package with the fixes you found. Thanks for the contribution :)

For problem shown the screenshot, I think you just have to add `flex: 1` to the style of the elements

```jsx
return (
  <GestureHandlerRootView style={{ flex: 1 }}>
    <View style={{ flex: 1 }}>
      <SvgEditor ref={canvasRef} svg={svg} />
    </View>
  </GestureHandlerRootView>
)
```

**Comment by mbaviera** [comment]
Hi @DevChanQ thanks for the support, it's actually working!

Regarding the toolbar, should it only appear when there is some text present in the image? Here it appears as follows:

<img width="445" alt="Captura de Tela 2024-03-25 às 09 09 47" src="https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/00d1e647-2995-489c-84ec-29e2616a727f">

Another question, when importing a larger svg, for example a logo, an error occurs. Is there any svg size limitation or any svg image tag limitation?

<img width="445" alt="Captura de Tela 2024-03-25 às 09 12 22" src="https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/eabb1f9d-2af5-4b72-a05e-0cd2a52c999d">

<img width="445" alt="Captura de Tela 2024-03-25 às 09 12 47" src="https://github.com/DevChanQ/react-native-svg-editor/assets/26506097/c3cec30e-3b55-4194-b4ec-1dde0cc701fa">

Once again, thank you very much for your work and support!

**Comment by DevChanQ** [comment]
The toolbar is a separate component that I didn't include in the source code as the intention is to encourage custom toolbar/ui to be built by utilising the editor component ref functions. I will consider open sourcing the toolbar as well but for now you can check out https://github.com/DevChanQ/react-native-svg-editor/blob/master/components/BaseSvgEditor.js . Most public functions that you could access are commented so you should get a sense of how to use them!

On the editor error alert, to be honest the editor is not complete, the svg spec isn't implemented fully but I tried to cover as much as possible. That's why contributions will be very much appreciated!

**Comment by gorankirovski** [comment]
This doesn't work in expo, it says I have to use development build which requires paid apple Developer account and also conflicts with react-native 0.74.5
